apiVersion: apps/v1
kind: Deployment
metadata:
  name: subsidyapp-backend-COLOR_LABEL
  namespace: subsidyapp-prod
  labels:
    app: subsidyapp-backend
    version: COLOR_LABEL
    environment: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: subsidyapp-backend
      version: COLOR_LABEL
  template:
    metadata:
      labels:
        app: subsidyapp-backend
        version: COLOR_LABEL
        color: COLOR_LABEL
        environment: production
    spec:
      containers:
      - name: subsidyapp-backend
        image: REGISTRY_PATH/backend:IMAGE_TAG
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: subsidyapp-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: subsidyapp-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: subsidyapp-secrets
              key: jwt-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: subsidyapp-secrets
              key: openai-api-key
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: subsidyapp-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: subsidyapp-secrets
              key: aws-secret-access-key
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: subsidyapp-config
              key: s3-bucket-name
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: subsidyapp-uploads-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: subsidyapp-logs-pvc
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: subsidyapp-backend-COLOR_LABEL
  namespace: subsidyapp-prod
  labels:
    app: subsidyapp-backend
    version: COLOR_LABEL
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: subsidyapp-backend
    version: COLOR_LABEL